//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TikTokDownloader {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TikTokDownloader.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attempt.
        /// </summary>
        internal static string Attempt {
            get {
                return ResourceManager.GetString("Attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open settings, find the application there and allow access to file storage manually.
        /// </summary>
        internal static string CanNotOpenSettingsInfo {
            get {
                return ResourceManager.GetString("CanNotOpenSettingsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No way to open settings.
        /// </summary>
        internal static string CanNotOpenSettingsTitle {
            get {
                return ResourceManager.GetString("CanNotOpenSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mail .
        /// </summary>
        internal static string ContatctMail {
            get {
                return ResourceManager.GetString("ContatctMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Telegram .
        /// </summary>
        internal static string ContatctTelegram {
            get {
                return ResourceManager.GetString("ContatctTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VK .
        /// </summary>
        internal static string ContatctVK {
            get {
                return ResourceManager.GetString("ContatctVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Developer contacts:.
        /// </summary>
        internal static string DeveloperContacts {
            get {
                return ResourceManager.GetString("DeveloperContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download page.
        /// </summary>
        internal static string DownloadActivityName {
            get {
                return ResourceManager.GetString("DownloadActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download images without watermark.
        /// </summary>
        internal static string DownloadImagesWithotWatermark {
            get {
                return ResourceManager.GetString("DownloadImagesWithotWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download images with watermark.
        /// </summary>
        internal static string DownloadImagesWithWatermark {
            get {
                return ResourceManager.GetString("DownloadImagesWithWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download images with watermark and user icon.
        /// </summary>
        internal static string DownloadImagesWithWatermarkAndUser {
            get {
                return ResourceManager.GetString("DownloadImagesWithWatermarkAndUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download thubnail without watermark.
        /// </summary>
        internal static string DownloadThubnailWithoutWatermark {
            get {
                return ResourceManager.GetString("DownloadThubnailWithoutWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files not found.
        /// </summary>
        internal static string FilesNotFound {
            get {
                return ResourceManager.GetString("FilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Third-party services are unavailable for reasons beyond the control of the application. If you cannot download for some time, contact the developer.
        /// </summary>
        internal static string GetDataFailedInfo {
            get {
                return ResourceManager.GetString("GetDataFailedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t get data.
        /// </summary>
        internal static string GetDataFailedTitle {
            get {
                return ResourceManager.GetString("GetDataFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Good.
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Tap to share button in TT.
        /// </summary>
        internal static string HelpInfo1 {
            get {
                return ResourceManager.GetString("HelpInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. Copy link.
        /// </summary>
        internal static string HelpInfo2 {
            get {
                return ResourceManager.GetString("HelpInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3. Past link to field behind.
        /// </summary>
        internal static string HelpInfo3 {
            get {
                return ResourceManager.GetString("HelpInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4. Tap to Download.
        /// </summary>
        internal static string HelpInfo4 {
            get {
                return ResourceManager.GetString("HelpInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на images without watermark.
        /// </summary>
        internal static string ImagesWithoutWaterMark {
            get {
                return ResourceManager.GetString("ImagesWithoutWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на images with watermark.
        /// </summary>
        internal static string ImagesWithWaterMark {
            get {
                return ResourceManager.GetString("ImagesWithWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на images with watermark and user icon.
        /// </summary>
        internal static string ImagesWithWaterMarkAndUser {
            get {
                return ResourceManager.GetString("ImagesWithWaterMarkAndUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change language 🇺🇸.
        /// </summary>
        internal static string LanguageFlag {
            get {
                return ResourceManager.GetString("LanguageFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Past link here.
        /// </summary>
        internal static string LinkHere {
            get {
                return ResourceManager.GetString("LinkHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main page.
        /// </summary>
        internal static string MainActivityName {
            get {
                return ResourceManager.GetString("MainActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New link finded.
        /// </summary>
        internal static string NewUrlFinded {
            get {
                return ResourceManager.GetString("NewUrlFinded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nod.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To fix the problem, you can reinstall the application and allow access, or allow access in the settings. Open application settings?.
        /// </summary>
        internal static string NoHaveFilePermissionsInfo {
            get {
                return ResourceManager.GetString("NoHaveFilePermissionsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No have permissions to file storage.
        /// </summary>
        internal static string NoHaveFilePermissionsTitle {
            get {
                return ResourceManager.GetString("NoHaveFilePermissionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No have permissions to file storage.
        /// </summary>
        internal static string NoHavePermissions {
            get {
                return ResourceManager.GetString("NoHavePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Past link to field.
        /// </summary>
        internal static string PastLinkToField {
            get {
                return ResourceManager.GetString("PastLinkToField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application can&apos;t work without file permissions.
        /// </summary>
        internal static string PermissionsDescardedInfo {
            get {
                return ResourceManager.GetString("PermissionsDescardedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permissions descarded.
        /// </summary>
        internal static string PermissionsDescardedTitle {
            get {
                return ResourceManager.GetString("PermissionsDescardedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved to downloads.
        /// </summary>
        internal static string SavedToDownloads {
            get {
                return ResourceManager.GetString("SavedToDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved to gallery.
        /// </summary>
        internal static string SavedToGallery {
            get {
                return ResourceManager.GetString("SavedToGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save failed, try again.
        /// </summary>
        internal static string SaveFailTryAgain {
            get {
                return ResourceManager.GetString("SaveFailTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound.
        /// </summary>
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на thubnails without watermark.
        /// </summary>
        internal static string ThubnailsWithoutWaterMark {
            get {
                return ResourceManager.GetString("ThubnailsWithoutWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I understend.
        /// </summary>
        internal static string Understend {
            get {
                return ResourceManager.GetString("Understend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на without watermark.
        /// </summary>
        internal static string WithoutWaterMark {
            get {
                return ResourceManager.GetString("WithoutWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на with watermark.
        /// </summary>
        internal static string WithWaterMark {
            get {
                return ResourceManager.GetString("WithWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
